apiVersion: v1
kind: Namespace
metadata:
  name: wishlist
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wishlist-data-folder
  namespace: wishlist
spec:
  capacity:
    storage: 5Gi # Match or exceed your PVC request
  accessModes:
    - ReadWriteOnce
  storageClassName: manual # This is the key
  hostPath:
    path: /Users/alexandermyltsev/k8s/wishlist/Data # Your chosen Mac folder
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wishlist-data
  namespace: wishlist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist
  namespace: wishlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
        - name: wishlist
          # Замените на ваш образ, например ghcr.io/<owner>/wishlist:latest
          image: ghcr.io/equillibrium/wishlist:latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: wishlist-data
              mountPath: /app/data
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: wishlist-data
          persistentVolumeClaim:
            claimName: wishlist-data
---
apiVersion: v1
kind: Service
metadata:
  name: wishlist
  namespace: wishlist
spec:
  selector:
    app: wishlist
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  type: ClusterIP

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wishlist
  namespace: wishlist
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wishlist.kotobars.ru`)
      kind: Rule
      services:
        - name: wishlist
          namespace: wishlist
          port: 80
          scheme: http
          passHostHeader: true
  tls:
    certResolver: letsencrypt
    domains:
      - main: "*.kotobars.ru"
        sans:
          - "kotobars.ru"